import { PDFParse } from 'pdf-parse';
import { readFileSync } from 'fs';
const PDF_PATH = process.env.TCF_SAMPLE_PDF;
if (!PDF_PATH) throw new Error('TCF_SAMPLE_PDF is not set — point it at one local listening PDF.');
const buf = readFileSync(PDF_PATH);
const parser = new PDFParse({ data: new Uint8Array(buf) });
const result = await parser.getText();
const lines = result.text.split('\n');
lines.slice(200, 450).forEach((l, i) => console.log(String(i+201).padStart(3), JSON.stringify(l)));
await parser.destroy();
